### ISSUE TITLE
macOS workaround to avoid `stringi` issues

### ISSUE THREAD

**Issue by grayskripko** [jimmyday12/fitzroy_data#2]
Some time ago I saw you used github actions in order to update your data. Later I even used your script as a prototype for my project. I was suprised why you used macOS as a system until I faced with problems with R tidyverse installation, that required stringi package. Stringi installation on linux was pain but I was able to overcome it with
```
install.packages("stringi", repos = "https://cran.rstudio.com")
```
after reading a lot in stringi github issues section.
Today I've found that macOS could be very expensive solution in terms of billable time so I suggest you to try to go back to linux system to save your minutes on github actions.

![image](https://user-images.githubusercontent.com/10427026/231236817-67b29ee2-6ff8-476d-b15e-5603341b9fe3.png)

From https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

**Comment by jimmyday12** [comment]
Thanks for the comment and hope you found it useful. I'm not sure its the best approach but it has worked for a while. 

In terms of billing - since this is a public repo, all Github Action minutes are free regardless of the platform used. I'm not sure if there would be other benefits for moving to Linux
